### ISSUE TITLE
Duplicate Claim Reviews caused by url (http vs https)

### ISSUE THREAD

**Issue by ypesk** [CIMPLE-project/converter#12]
Some Claim Reviews are duplicated because the uri is generated using the claim text, the url of the review, and the rating. In some cases, the url are different in the protocol, example:

https://data.cimple.eu/claim-review/f9374d106b6dea97dbf2cc92c4c2a124f07f76043c87bf0a6c3cc89d
https://data.cimple.eu/claim-review/5a54143bd1c67713dc50ab7ce0d97d524808432eb734c0c5df4465a8

other example:
https://data.cimple.eu/claim-review/dab4dcd607aba39cfac63522185f2a5fad3e1dd2bbfc001608f3b8e4
https://data.cimple.eu/claim-review/459d40b82a95301011b8db4d9bc16aa0c07fc05ff868608a54195079

The Claim Reviews affected seem to always have a related tweet attached, so it is likely a bug when adding the static datasets (either birdwatch or check-that), I will have a look

Removing the protocol from the generation of the uri will likely fix the problem.

**Comment by ypesk** [comment]
Also, we should lower case the URL of the claim review. Right now, the generation of the URI is based on the URL of the review and is case sensitive. I found examples where the URL are both lower-cased and upper-cased which create two different URIs for the same claim-review.

Example:
https://data.cimple.eu/claim-review/1931e35ffdfa3e6c10c01adf8aac71c0cb42b3fa4940ef8d6ff2b6c1
https://data.cimple.eu/claim-review/8825516c8671a9e425a86e3169665b981304cae915ebb9a965d5c8a7

Also some ClaimReviews refer to a specific header in the URL, see:
http://data.cimple.eu/claim-review/bda240bab8bb783f32ed828c6483e3a274b7aa0216cfe08b2b9ac03b
http://data.cimple.eu/claim-review/be22ca459e5f25c9979249e246ed309d5ad728c35bca6dbcef8b4479

However, the reviews are the same, maybe we can merge them

**Comment by rtroncy** [comment]
+1 to: normalize the case (lower case the URL) and normalize the protocol (to http even if this is https) before generating the UUID so get rid of these duplicates. @ypesk can you do this?

**Comment by ypesk** [comment]
I am investigating further problems with similar URL like:
https://data.cimple.eu/claim-review/8c858556521b43d7c5be82cd523d6f3e1d6561fe6dd63c9594130968
https://data.cimple.eu/claim-review/e4d36c6c40572501d5d9a8ed279d35dcd9bcc11eec36210d22175c07

Where the URL contains "?lang=de"

Or these two:
https://data.cimple.eu/claim-review/f1ab2b1fe14b249b347e2f989743da31709c4ded21598324abd4928c
https://data.cimple.eu/claim-review/cf934993a60c9a07310c10bc6268e7328ed2e1aeb2c5823eb368237b

Where the URL are different, but resolve to the same page. We actually didn't manage to retrieve the content of this article, probably because of the Cloudflare protection.

I will try to fix it once I know the whole list of issues
